### ISSUE TITLE
scripts/loadup-full.sh fails if not connected to the clone directory

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#2050]
On my mac running sequoia, but I am connected to my Medley working directory, not the clone master.  I have copied all of the new scripts from the clone master.  It seems that it really wants to be in a clone.

Here is the shell transcript until it breaks:

kaplan@Ron-Macbook-Air git-medley % cdwm
kaplan@Ron-Macbook-Air working-medley % scripts/loadup-full.sh
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
>>>>> START loadup-init
"/Users/kaplan/Local/medley3.5/working-medley/../maiko/darwin.aarch64/lde" "/Users/kaplan/Local/medley3.5/working-medley/internal/loadups/starter.sysout" -id "loadup_1" -title "Medley Interlisp :: loadup_1" -g 1024x768 -sc 1024x768 -noscroll
MEDLEYDIR: "/Users/kaplan/Local/medley3.5/working-medley"
LOGINDIR: "/tmp/loadups-78991/logindir"
GREET FILE: "/tmp/loadups-78991/loadup-init.init"
VMEM FILE: "/tmp/loadups-78991/logindir/vmem/lisp_loadup_1.virtualmem"
+++++ SUCCESS +++++
..... files created .....
-rw-r--r--  1 kaplan  wheel  4316160 Feb 27 10:21 /tmp/loadups-78991/init.dlinit
-rw-r--r--  1 kaplan  wheel  119329 Feb 27 10:21 /tmp/loadups-78991/init.dribble
-rw-r--r--  1 kaplan  wheel  4169728 Feb 27 10:21 /tmp/loadups-78991/init.sysout
-rw-r--r--  1 kaplan  wheel  55805 Feb 27 10:21 /tmp/loadups-78991/RDSYS
-rw-r--r--  1 kaplan  wheel  42969 Feb 27 10:21 /tmp/loadups-78991/RDSYS.LCOM
-rw-r--r--  1 kaplan  wheel  89162 Feb 27 10:21 /tmp/loadups-78991/I-NEW
-rw-r--r--  1 kaplan  wheel  70633 Feb 27 10:21 /tmp/loadups-78991/I-NEW.LCOM
<<<<< END loadup-init

fatal: not a git repository (or any of the parent directories): .git
>>>>> START loadup-mid-from-init
"/Users/kaplan/Local/medley3.5/working-medley/../maiko/darwin.aarch64/ldeinit" "/tmp/loadups-78991/init.dlinit" -id "loadup_1" -title "Medley Interlisp :: loadup_1" -g 1024x768 -sc 1024x768 -noscroll -NF
MEDLEYDIR: "/Users/kaplan/Local/medley3.5/working-medley"
LOGINDIR: "/tmp/loadups-78991/logindir"
GREET FILE: "/Users/kaplan/Local/medley3.5/working-medley/greetfiles/NOGREET"
VMEM FILE: "/tmp/loadups-78991/init-mid.sysout"

**Comment by fghalasz** [comment]
Fixed in PR#2052

**Comment by rmkaplan** [comment]
It looks 2052 was merged, and I am running by working directory with those scripts.  But it still fails, maybe for a different reason.  It makes the init.sysout, but then just stops with a blank screen on the next phase.

kaplan@Ron-Macbook-Air working-medley % scripts/loadup-all.sh
>>>>> START loadup-init
"/Users/kaplan/Local/medley3.5/working-medley/../maiko/darwin.aarch64/lde" "/Users/kaplan/Local/medley3.5/working-medley/internal/loadups/starter.sysout" -id "loadup_1" -title "Medley Interlisp :: loadup_1" -g 1024x768 -sc 1024x768 -noscroll
MEDLEYDIR: "/Users/kaplan/Local/medley3.5/working-medley"
LOGINDIR: "/tmp/loadups-31553/logindir"
GREET FILE: "/tmp/loadups-31553/loadup-init.init"
VMEM FILE: "/tmp/loadups-31553/logindir/vmem/lisp_loadup_1.virtualmem"
+++++ SUCCESS +++++
..... files created .....
-rw-r--r--  1 kaplan  wheel  4317184 Mar  4 16:30 /tmp/loadups-31553/init.dlinit
-rw-r--r--  1 kaplan  wheel  119333 Mar  4 16:30 /tmp/loadups-31553/init.dribble
-rw-r--r--  1 kaplan  wheel  4170752 Mar  4 16:30 /tmp/loadups-31553/init.sysout
-rw-r--r--  1 kaplan  wheel  55805 Mar  4 16:30 /tmp/loadups-31553/RDSYS
-rw-r--r--  1 kaplan  wheel  42969 Mar  4 16:30 /tmp/loadups-31553/RDSYS.LCOM
-rw-r--r--  1 kaplan  wheel  89162 Mar  4 16:30 /tmp/loadups-31553/I-NEW
-rw-r--r--  1 kaplan  wheel  70633 Mar  4 16:30 /tmp/loadups-31553/I-NEW.LCOM
<<<<< END loadup-init

**Comment by rmkaplan** [comment]
P.S.  I used cp to copy scripts/ from the clone directory to my working directory, to avoid any version or protection problems from GITFNS.
