### ISSUE TITLE
run-medley -nogreet still greets

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#462]
@rmkaplan reported https://github.com/Interlisp/medley/pull/453#pullrequestreview-747279243

which is related but different problem. The code in GREETFILENAME (on APUTDQ) is the basis for what GREET does.
It was written for a world where there were sites with sysadmins who would manage site-specific initialization (shared by all users) and then individual init files.

(GREETFILENAME T) returns the site init file and it looks at "LDEINIT", {DSK}/usr/local/lde/site-init.lisp, or {DSK}INIT.ext for ext=LCOM, DFASL, LISP

**Comment by nbriggs** [comment]
It's still a useful concept -- when you install a release, the "site init file" should incorporate the information about where the installation was unpacked, where the fonts are, and anything else that needs to be set for every installation. Then your personal preferences should go in the user greet files

**Comment by masinter** [comment]
I agree it's a useful concept. It's the implementation that doesn't fit. It also got tangled with loadup automation.

**Comment by masinter** [comment]
it would be nice if the result would run with starter.sysout and the venuesysouts. So requiring a new version of GREET would make trouble.

What if -nogreet set LDEINIT to medley/greetfiles/nogreet
and set up nogreet to (P (AND (STKPOS 'GREET) (RETFROM 'GREET)))
(need to close the 'nogreet' input stream)

I'm guessing the use case for -nogreet is to do manual loadups ? It was added not so long ago

**Comment by nbriggs** [comment]
Can the "nogreet" system greet file set USERGREETFILES to NIL to avoid user greet files being loaded.

**Comment by nbriggs** [comment]
It seems wrong that if I do:
```
LDEINIT="" ./run-medley tmp/lisp.sysout
```
then `(UNIX-GETENV "LDEINIT")` still returns `"/Users/briggs/Projects/medley/greetfiles/SIMPLE-INIT.;1"` and that if I do
```
./run-medley tmp/lisp.sysout --nogreet
```
then `(UNIX-GETENV "LDEINIT")` returns the string `"NIL"` instead of the atom NIL.

**Comment by nbriggs** [comment]
I believe that in the "nogreet" case in run-medley it should do "unset LDEINIT" rather than setting it to the empty string.

**Comment by nbriggs** [comment]
Try this patch and see if the result is what you want.  If LDEINIT is not set then it will set it to the SIMPLE-INIT, but if it is set to anything, including the empty string, it will leave it alone, unless there is a `--[no]greet` in which case it will either unset it or override it with the given parameter.

```
diff --git a/run-medley b/run-medley
index 9ab722e..0072565 100755
--- a/run-medley
+++ b/run-medley
@@ -45,16 +45,14 @@ if [ -z "$LDEDESTSYSOUT" ] ; then
     fi
 fi
 
-if [ -z "$LDEINIT" ] ; then
-    export LDEINIT="$MEDLEYDIR/greetfiles/SIMPLE-INIT"
-fi
+export LDEINIT=${LDEINIT-"$MEDLEYDIR/greetfiles/SIMPLE-INIT"}
 
 export LDEKBDTYPE=x
 
 while [ "$#" -ne 0 ]; do
     case "$1" in
         "-nogreet" | "--nogreet")
-            export LDEINIT=""
+            unset LDEINIT
             ;;
         "-greet" | "--greet")
             export LDEINIT="$2"
```

**Comment by masinter** [comment]
![image](https://user-images.githubusercontent.com/1116587/132291545-33e3711e-a214-4e3d-a079-416190620fcc.png)
so you have to turn off two files; (GREETFILENAME T) and (GREETFILENAME (USERNAME))
Turning off the site init is hard -- {DSK}/usr/local/lde/site-init.lisp is wired in, as is the loop prompting for a system init file.
better to give it something it can chew on (i..e., INFILEP).

setting USERGREETFILES to NIL looks promising. But note that USERGREETFILES is (re)set by MEDLEY-INIT-VARS (fn and var) because it has environment-sensitive values.

![image](https://user-images.githubusercontent.com/1116587/132295183-2a62e0d3-2e2d-48a0-8eab-3c50ccf9028d.png)

**Comment by nbriggs** [comment]
It seems to me that the code in MEDLEYDIR, or at least MEDLEY-INIT-VARS should be in the site init file... not preloaded in the sysouts as they're made.

**Comment by masinter** [comment]
leaving them out of the sysouts would make the sysouts not work well when moved

**Comment by rmkaplan** [comment]
I don’t understand all the ins and outs of this, I had a -nogreet set up that worked for years in my own loadups on top of a full (at least, that’s what I thought).

You always need to have a site greeting file to do the loadup, and that has to set the local variables to what we need for the loadup.  A user running the constructed makesys’s in our local environment presumably wants those variables set in the same way.  Medleydir parameterizes that.  In other words, we need to load the site greeting file in all circumstances.

So simple-init is common to both scenarios (system loadup and user start-up).  Is the strategy here essentially to provide a separate system-loadup-init file that wraps the loading of simple-init in something that suppresses the loading-user’s personal init, but then leaves the loadup ready for both the site greeting file and also the personal init the next time it is started up?

If the loadup-wrapper sets USERGREETFILES to NIL after loading simple-init (which sets USERGREETFILES to a locally desired value), wouldn’t that be enough to suppress the personal init?  On user startup, the site-greetfile’s setting would reestablish the desired value.

**Comment by masinter** [comment]
i had to add it to the sysout in order for a sysout to work for anyone other than the person doing the loadup.
Another possibility would be to introduce an "abbreviation" device so that {MEDLEY}<fonts>displayfonts> would be relative to MEDLEYDIR and {LOGIN}lisp.virtualmem would be relative to LOGINDIR.  Then we wouldn't need to change all the variables that had absolute pathnames.

**Comment by nbriggs** [comment]
> it would be nice if the result would run with starter.sysout and the venuesysouts.

If that's a goal, then it can't depend on things that we're adding to the sysouts.

**Comment by masinter** [comment]
I updated PR #453 to include changes for run-medley -nogreet and loadup-full.sh.

**Comment by rmkaplan** [comment]
After doing a loadup

**Comment by rmkaplan** [comment]
When I do a loadup and start up the full with -NOGREET, it tells me that it is loading NOGREET.

But my INIT has previously been loaded, even though it doesn’t show as being loaded.

So, problem still appears not to be solved.  The full.sysout is already corrupted by me.

**Comment by masinter** [comment]
The situation is over-constrained.
The problems are rooted in the idea of using LDEINIT to feed some actions to a sysout during the LOADUP process.

I think instead we could have a variable (LOADUP?) which if set, is used to do the loadup, and also turn off GREET.

**Comment by rmkaplan** [comment]
The strategy should also work for building loadups (like LFG) on top of lisp and full sysouts.  And I think you also wanted it to work for old sysouts, like the venuesysout, so can’t depend on something already in the sysout.

Suppose you set LDEINIT to a file (like LOADUP-FULL or LOADLFG) that loads the site-greeting file, after which it sets the USERGREETFILES to NIL and continues the rest of its loadup.  Wouldn’t that suppress the loadup-user’s personal greeting?

You might want it not to have the name of the site-greeting file built in, so the same set up could be run in different environments.  To that end, a second unix variable LDESITEINIT could be set to the name of that file (SIMPLE-INIT in our case), and the LDEINIT file (LOADUP-FULL) could load (UNIX-GETENV “LDESITEINIT”)) to start things off (maybe wrapped with MEDLEYDIR).

The sysout would end up with USERGREETFILES set to NIL, but that should be OK.  That will be set up, as it should be, by whatever LDEINIT site-greeting file is used when the sysout is started up for a new user in a new environment.

**Comment by nbriggs** [comment]
I believe the intent was that `LDEINIT` point to the site-int, and if that isn't set or the file it points to doesn't exist then it would fall back to "{DSK}/usr/local/lde/site-init.lisp" and if that doesn't exist then it tries "{DSK}INIT.[one of the compiled file extensions, or LISP]".   In the normal case, the site-init file should set up the USERGREETFILES, any site-specific variables like lists of printers, etc. etc.  That seems to match up with what Ron was saying, though I don't think we need to use a separate LDESITEINIT environment variable.   That's the strategy that the code that's in the lisp.venuesysout uses also.

**Comment by rmkaplan** [comment]
It may be better to deprecate the greetfiles/simple-init set up that we have now in favor of the fixed search sequence and set of names for the basic site-greeting file.  Then at least we wouldn’t have to have a separate variable to point ot the site greeting file when in fact you are using the LDEINIT to wrap something else around that (including nuking the USERGREETFILES).

But the current search path (in (GREETFILENAME T)) isn’t quite compatible with the world of git cloning, where the search really should be relative to the MEDLEYDIR that points to the respository.  I don’t think it is a good idea to have the Medley site file in a system-level location (like /usr/ or even whatever {DSK} maps to).  All the medley stuff should be local to the repository.

If the true site-greeting file (with fonts, directories, USERGREETFILES, printers) can be located according to built-in conventions, and the loadup-file in LDEINIT wants to share that information without duplicating it, then the loadup-file must have a way of skipping the cyclical LDEINIT option when running the GREETFILENAME search-sequence.

So, is there a way of unsetting LDEINIT from inside Lisp?  If there is, then a loadup file provided in LDEINIT could first remove itself from LDEINIT, load the site-greeting file by (MEDLEYDIR (GREETFILENAME T)), set USERGREETFILES to NIL, and then do whatever it wants to do.

**Comment by masinter** [comment]
```
grep -lri ldeinit .
./sources/APUTDQ
./sources/APUTDQ.LCOM
./sources/ADIR
./sources/ADIR.LCOM
./scripts/loadup-mid-from-init.sh
./docs/Sun Users Guide/3-GETTING-STARTED.TEDIT
./docs/Sun Users Guide/GLOSSARY.TEDIT
./docs/Sun Users Guide/INDEX.TEDIT
./docs/Sun Users Guide/APP-A-INSTALL-HINTS.TEDIT
./docs/html-sunguide/Sun-Users-Guide_files/content.htm
./greetfiles/initcommands.txt
./run-medley
./library/INIT.MAIKO
```
plus all loadups/ sysouts and a bunch of files under "obsolete/sunloadup/"

**Comment by nbriggs** [comment]
>But the current search path (in (GREETFILENAME T)) isn’t quite compatible with the world of git cloning, where the search really should be relative to the MEDLEYDIR that points to the respository.  I don’t think it is a good idea to have the Medley site file in a system-level location (like /usr/ or even whatever {DSK} maps to).  All the medley stuff should be local to the repository.

Working in the repository is not the model that (most) people expect, and should be discouraged -- if you're building the system "from source" you may git clone, build it, and then install it somewhere else.  /usr/local is the place for systems that, on a mac, aren't packaged as "applications" and is the normal place to install on Linux and FreeBSD.  If the application is just a few executables/libraries/config files  you'd use /usr/local/bin, /usr/local/lib, /usr/local/etc  but if the application is large collection of files (as Medley is) one would expect /usr/local/<application>/{bin,lib} and so on.   When we're packaging "releases" on github, those releases don't get installed through git cloning.

It really still works the same way that it did back at PARC in the 80's.  You start with a pre-built sysout, now instead of a remote reference to the lispusers and library and sources files you grab a copy to put on your local disk, and you proceed from there.   If you find you want to change (or add) something there's a different mechanism for contributing it (git and the github tools) vs making a copy available to the Lisp group and asking them to add or replace it.
